# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"
    
    - name: Install dependencies
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        poetry install
        
    - name: ruff-action
      # You may pin to the exact commit or the version.
      # uses: astral-sh/ruff-action@d0a0e814ec17e92d33be7d24dd922b479f1bcd38
      uses: astral-sh/ruff-action@v1.1.1
      #with:
      #  # Arguments passed to Ruff. Use `ruff --help` to see available options. Defaults to `check`.
      #  args: # optional, default is check
      #  # Source to run Ruff. Defaults to the current directory.
      #  src: # optional, default is .
      #  # The version of Ruff to use, e.g., `0.6.0` Defaults to the latest version.
      #  version: # optional, default is 
      #  # Whether to only run Ruff on changed files. Defaults to `false`.
      #  changed-files: # optional, default is false
                
    - name: Test with pytest
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        poetry run pytest
